version: '3'
services:

  app1:
    image: nicopaez/password-api
    ports:
    - "3001:3000"

  app2:
    image: nicopaez/password-api
    ports:
    - "3002:3000"

  nginx:
    image: nginx:1.22.0
    ports:
    - 4444:8080
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - app1
    - app2
